version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - 'zookeeper_data:/bitnami/zookeeper'
  kafka1:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://:29092,EXTERNAL://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - BOOTSTRAP_SERVERS=kafka1:29092,kafka2:29093,kafka3:9094,kafka4:9095
    volumes:
      - 'kafka1_data:/bitnami/kafka'
  kafka2:
    image: 'bitnami/kafka:latest'
    ports:
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://:29093,EXTERNAL://:9093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://:29093,EXTERNAL://localhost:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - BOOTSTRAP_SERVERS=kafka1:29092,kafka2:29093,kafka3:9094,kafka4:9095
    volumes:
      - 'kafka2_data:/bitnami/kafka'
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka1:29092"
    depends_on:
      - kafka1
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - zookeeper
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:29092,kafka2:29093,kafka3:9094,kafka4:9095
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
volumes:
  zookeeper_data:
    driver: local
  kafka1_data:
    driver: local
  kafka2_data:
    driver: local
